server:
  port: 8882

eureka:
  client:
    service-url:
      defaultZone: http://eureka-peer2:10087/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 8